language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - hhvm

matrix:
  fast_finish: true

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"

script:
  - codecept build && codecept run
